### ISSUE TITLE
add CreateApplication() to config.go

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#180]
Currently,  config.go does not have any `CreateApplication()` method which creates an application. An application is created using `SetActiveApplication()` which does 2 things, creates an application and sets it as active. This behavior should be decoupled.

This will help us setting an application as active without creating it, and the logic like `	exists, err := application.Exists(appName)` which should not be there in cmd/application.go, will be removed

**Comment by kadel** [comment]
> Currently, config.go does not have any CreateApplication() method which creates an application. An application is created using SetActiveApplication() which does 2 things, creates an application and sets it as active. This behavior should be decoupled.

agreed

This will help us setting an application as active without creating it, and the logic like exists, err := application.Exists(appName) which should not be there in cmd/application.go, will be removed

not really. You will still have to check it there. You can't call `application.Exists(appName)`  from `config` that would be wrong and messy (and also impossible because of circula dependencies).
